### ISSUE TITLE
[MainMenu-API] 베스트 만찬 요청 처리

### ISSUE THREAD

**Issue by MJbae** [skawnkk/sidedish#10]
[TASK]
1. 베스트 만찬 요청에 대한 비지니스 로직 처리 결과를 받아서 response body에 담아서 클라이언트에게 전달한다.
2. 해당 요청에 대한 테스트 코드를 작성한다.
3. 다섯가지 탭의 요청에 해당하는 dish를 DB에서 조회한다.
4. 매 요청에 따라 3가지의 dish를 랜덤하게 선택한다.

[인수조건]
1. response body에는 detail_hash, title, description, n_price(or s_price) 필드가 포함되어 있어야 한다.
2. 다섯가지 탭에 따라 dish를 분류할 수 있어야 한다.
3. 테스트 코드를 통과한다.

**Comment by MJbae** [comment]
토의할 부분: Response Format에 대한 부분

**Comment by MJbae** [comment]
토의할 부분: 베스트 만찬의 경우 Mock API에는 category_id를 기준으로 각 카테고리에 3개씩 dish가 나뉘어져 있음. Mock Data를 그대로 따라갈 것인지, 아니면 category를 우리가 임의로 분류해서 서버에서 처리할 것인지?

**Comment by eNoLJ** [comment]
Mock API와 동일하게 category_id를 기준으로 3개씩 보내도록 결정
