### ISSUE TITLE
[Detail-API] 주문하기 요청 처리

### ISSUE THREAD

**Issue by MJbae** [skawnkk/sidedish#12]
[TASK]
1. 재고와 주문 개수를 계산하여 정상 주문과 비정상 주문을 구분한다.
2. 정상 주문일 경우, 주문 개수에 해당하는 값을 재고에서 뺀다.
3. 비정상 주문일 경우, 예외를 발생시키고 에러 메시지를 클라이언트에게 전달한다.

[인수조건]
1. 정상 주문과 비정상 주문을 구분할 것

**Comment by eNoLJ** [comment]
정상 주문일 경우 재고를 떨어뜨리고 hash값과 남은 재고를 보낸다.
비전상적인 주문일 경우 400번 에러를 보낸다.
