### ISSUE TITLE
[DetailPage] useState를 여러번 사용했을시, 특정값이 변경됐을 때 해당 컴포넌트만 렌더링되는 방법?  

### ISSUE THREAD

**Issue by skawnkk** [skawnkk/sidedish#65]
useState를 여러번 사용했을시, 
ex) a, b, c에 대해 useState를 사용했고 a값이 변경되었을 때 a만 렌더링되게 하고 싶은데
b, c가 새로 컴포넌트를 그려주고있는것 같다.

a만 렌더링되는 방법? 뭐ㅈ\?

**Comment by wade3420** [comment]
UseMemo...?
