### ISSUE TITLE
[Category-API] 카테고리별 요청 처리

### ISSUE THREAD

**Issue by MJbae** [skawnkk/sidedish#7]
[TASK]
네 가지 카테고리(main, course, soup, side)에 따른 dish를 DB에서 조회한다.
카테고리별 요청에 대한 비지니스 로직의 결과를 받아서 response body로 전송한다.

[인수조건]
response body에 detail_hash, image, delivery_type, title, description, s_price 필드가 있어야 한다.

**Comment by MJbae** [comment]
의문점: mock api를 보면 s_price는 필수적으로 존재하지만 n_price는 선택적으로 존재함. 그런데 개념상 n_price가 필수적으로 존재해야 하지 않나?
의견을 정리 필요: s_price를 not null로 지정? or n_price를 not null로 지정하고 data를 추가적으로 가공?

**Comment by eNoLJ** [comment]
n_price를 기본 가격으로 지정,
s_price는 default value로 0으로 지정
