### ISSUE TITLE
[ItemCard] 목데이터로 샘플 작성 (이벤트효과 제외)

### ISSUE THREAD

**Issue by skawnkk** [skawnkk/sidedish#9]
목데이터로 상품 샘플 카드 작성
-이미지 크기는 L/ S 구분되어있는가
-할인 정보/정가 구분
-이벤트 벳지 유무 체크

* 메인 메뉴 만드는데 안에 내용물이 없으니까 만들게 없더라고요..  요고까지 하겠습니다 : )

**Comment by wade3420** [comment]
아 그렇군요! ㅜㅜ 많은 것을 그럼 제가 헤드까지 작업하겠습니다

**Comment by skawnkk** [comment]
구현완료 (but 정가부분 수정확인할 것)
